name: Deploy Project 2 PHP to Somee
on:
  push:
    branches: [ main ]
    paths:
      - 'project-2-php-ftp/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Deploy to Somee Hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 155.254.244.34
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./project-2-php-ftp/
          server-dir: www.thuhuong.somee.com/
          
          # DÒNG QUAN TRỌNG NHẤT: Ra lệnh xóa sạch file cũ trước khi upload
          dangerous-clean-slate: true
